Hide stderr of mpv
mov-cli/mov-cli pull request #362
Opened 2024-09-27 22:20 UTC by yesseruser

Fixes #361.

2024-09-28 20:31 UTC, THEGOLDENPRO requested changes
Can you check out my comment? Once you complete that I'm happy to merge. 😊

2024-09-28 20:31 UTC, THEGOLDENPRO commented on mov_cli/players/mpv.py
> +            return subprocess.Popen(default_args + self._get_args(self.platform, media), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
We only want the stdout and stderr to be eaten when mov-cli is not in debug mode, similar to what we did to [here](https://github.com/mov-cli/mov-cli/pull/362/commits/c05b64bb560eafdf5ca0295be6b57b99f608a2ae#diff-026d99f365876dcf4e513f759692d1406291cde3409e726daa12c4570298fbe0R55-R56).

Also are you sure this works? I would have:
```python
stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT
```

2024-09-30 05:50 UTC, yesseruser commented on mov_cli/players/mpv.py
> +            return subprocess.Popen(default_args + self._get_args(self.platform, media), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
I suppose your version is more clear. But not eating stdout in debug mode would mean the bug would still be present.

PIPE should eat the output, but return it as a tuple (stdout, stderr) from the Popen function. Is it being printed after returning and exiting?

2024-09-30 09:57 UTC, THEGOLDENPRO commented
Thanks, I'll confirm and merge when I get home later today. 👍

2024-09-30 21:57 UTC, THEGOLDENPRO commented on mov_cli/players/mpv.py
> +            return subprocess.Popen(default_args + self._get_args(self.platform, media), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Oh sorry, I didn't see your comment earlier when I was on github mobile. Anyways about your comment, I had forgotten what PIPE did that's why I was unsure on your implementation earlier; thanks for informing me.

>  Is it being printed after returning and exiting?
Oh yeah also no we are not using the output from the tuple anywhere in mov-cli at the moment so `DEVNULL` also works.

2024-09-30 21:58 UTC, THEGOLDENPRO commented
Just tested the pr and everything works as expected, so I'm now merging this. I'm also gonna back port this fix to v4.4 so you don't have to wait for the next major release.

2024-09-30 21:58 UTC, merged